version: '3.4'

services:
  app:
    build:
        context: ./
        dockerfile: ./Dockerfile
    ports:
    - 8085:80
    depends_on:
    - postgres
  postgres:
    restart: always
    image: postgres:10.7
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234567
    ports:
      - 5436:5432